site_name: Testing Documentation Wiki

site_name: Testing Documentation Wiki

theme:
  name: material
  logo: https://www.sicarx.com/images/new/logo_white.webp
  palette:
    # Modo oscuro (Dracula-like)
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: light-blue
      toggle:
        icon: material/lightbulb-outline
        name: Cambiar a modo claro
    # Modo claro
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: light-blue
      toggle:
        icon: material/lightbulb
        name: Cambiar a modo oscuro
  
  features:
    - navigation.sections
    - navigation.expand
    - navigation.instant
    - navigation.tracking
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.tooltips

plugins:
  - search
  - i18n:
      default_language: es
      languages:
        - locale: es
          name: Español
          build: true
          default: true
        - locale: en
          name: English
          build: false

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
  - tables
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - css/custom.css